version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/lawnstarter-frontend/Dockerfile
    restart: always
    ports:
      - 3000:3000
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/lawnstarter-backend/Dockerfile
    restart: always
    ports:
      - 8080:8080

