import { SearchBox } from "@src/components/searchBox";
import { SearchResults } from "@src/components/searchResults";
import { useSearchStore } from "@src/stores/search.store";
import Head from "next/head";
import { useEffect } from "react";

const Home = () => {
	useEffect(() => {
		useSearchStore.getState().clear();
	}, []);

	return (
		<>
			<Head>
				<title>LawnStarter Test</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<SearchBox />
			<SearchResults />
		</>
	);
};

export default Home;
